import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { userProfile, preferences } = await req.json()
    
    // 1. Construct the Prompt for Gemini
    const prompt = `
      You are an elite fitness coach. Create a workout session based on the user's details.
      
      User Profile:
      - Goal: ${preferences.goal}
      - Target Muscle/Focus: ${preferences.target_muscle || 'Full Body'}
      - Level: ${userProfile.fitness_level || 'Intermediate'}
      - Equipment: ${preferences.equipment || 'Full Gym'}
      - Duration: ${preferences.duration} minutes
      - Injuries/Concerns: ${preferences.focus || 'None'}

      RULES:
      1. Return ONLY valid JSON. No markdown, no backticks.
      2. The structure must match this interface:
      {
        "workout_name": "Creative Name String (e.g. 'Chest Destroyer' or 'Full Body Blast')",
        "description": "Brief strategy description explaining why these exercises were chosen for the target muscle.",
        "estimated_duration": "number (minutes)",
        "exercises": [
          {
            "name": "Exercise Name",
            "sets": number,
            "reps": "string (e.g. '12' or '12-15')",
            "rest": "string (e.g. '60s')",
            "tips": "Brief form tip"
          }
        ]
      }
      3. Focus heavily on the '${preferences.target_muscle || 'Full Body'}' muscle group if specified.
      4. Ensure exercises are safe for the stated injuries.
      5. Provide ${Math.floor(parseInt(preferences.duration || '60') / 10)} to ${Math.floor(parseInt(preferences.duration || '60') / 7)} exercises.
    `

    // 2. Call Google Gemini API
    // Using environment variable for security, with fallback for development
    const API_KEY = Deno.env.get('GEMINI_API_KEY') || 'AIzaSyCjyzrSpfdw3Kh0pfUum6oHkUV-1oJCdIY';
    
    if (!API_KEY) {
      throw new Error('Missing GEMINI_API_KEY environment variable');
    }
    
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          responseMimeType: "application/json"
        }
      }),
    })

    const aiData = await response.json()
    
    if (aiData.error) {
      throw new Error(aiData.error.message)
    }

    // 3. Parse the content
    // Gemini returns the text in candidates[0].content.parts[0].text
    let generatedText = aiData.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error('No content generated by AI');
    }

    // Clean up markdown if Gemini adds it despite instructions
    generatedText = generatedText.replace(/```json\n?/, '').replace(/```/, '').trim();

    const generatedWorkout = JSON.parse(generatedText)

    return new Response(
      JSON.stringify(generatedWorkout),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Error:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
